export const baseURL = "http://127.0.0.1:8000/api/v1/";
export const registrationEndpoint = baseURL + "auth/registration/";
export const loginEndpoint = baseURL + "auth/login/";
export const get_auth_user = baseURL + "auth/user/";
export const logout_user = baseURL + "auth/logout/";
export const get_user_details = baseURL + "users/"
export const get_auth_user_details = baseURL + "auth/"
export const    post_routes = baseURL + "posts/"
export const search_user = baseURL + "users/"
export const follow_user = baseURL + "users/follow/";
export const unfollow_user = baseURL + "users/unfollow/";
