# Generated by Django 2.2.15 on 2020-08-22 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20200822_1417'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='follow.Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
