# Generated by Django 2.2.15 on 2020-09-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200901_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='follower',
        ),
    ]
