# Generated by Django 2.2.15 on 2020-09-03 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20200822_1417'),
        ('users', '0005_auto_20200903_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follower',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='follower', through='follow.Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
