# Generated by Django 2.2.15 on 2020-09-03 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200903_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='follow.Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
